 Style/FrozenStringLiteralComment:
   Enabled: false
 
 Style/StringLiterals:
   EnforcedStyle: double_quotes

   # AllCops:
# Include:
# - Rakefile
      #- config.ru
      #  - lib/**/*.rake
      #Exclude:
      #- db/schema.rb
 
      #Style/StringLiterals:
      #EnforcedStyle: double_quotes
  
      #Style/FrozenStringLiteralComment:
      #Enabled: false

      #Rails:
      #Enabled: true
