ClassLength:
  Max: 100

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
   EnforcedStyle: double_quotes

Style/MixinUsage:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: "map"
    collect!: "map!"
    inject: "reduce"
    detect: "find"
    find_all: "select"

Layout/TrailingBlankLines:
  Enabled: false

Layout/TrailingWhitespace:
  Exclude: 
    - "config/environments/production.rb"
    - "config/environments/developmemt.rb"

Layout/AlignParameters:
  Enabled: false

Layout/ClassStructure:
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - public_methods
      - protected_methods
      - private_methods

Metrics/MethodLength:
  Max: 8

Metrics/LineLength:
  Exclude:
    - "config/*"
    - "config/environments/*.rb"
    - "spec/rails_helper.rb"
