Style/FrozenStringLiteralComment:
  Enabled: false
 
Style/StringLiterals:
   EnforcedStyle: double_quotes

Layout/TrailingBlankLines:
  Enabled: false

Layout/ClassStructure:
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - public_methods
      - protected_methods
      - private_methods

Style/CollectionMethods:
  PreferredMethods:
    collect: "map"
    collect!: "map!"
    inject: "reduce"
    detect: "find"
    find_all: "select"
